name: spritexp
description: Kinda like a regular expression language, but for Sprites.
version: 0.1.0
repository: https://github.com/erickzanardo/spritexp

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: '>=3.10.0'

dependencies:
  flame: ^1.8.2
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ">=0.3.0 <2.0.0"
  very_good_analysis: ^5.0.0
